### ISSUE TITLE
大神你好

### ISSUE THREAD

**Issue by magic007** [lspCoder/yida#1]

**Comment by magic007** [comment]
Bmob 有模块化引入方式啊。

由于之前的js库臃肿，新的基于ES6写的， 不依赖第三方库， 我们出了，新夸平台SDK（开源），小程序，快应用，H5，nodejs，同用一个SDK

包引入方式

安装

npm install hydrogen-js-sdk
引入

import Bmob from "hydrogen-js-sdk";


具体文档，官网js文档也是这一份。

https://bmob.github.io/hydrogen-js-sdk/#/?id=%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8-1

**Comment by lspCoder** [comment]
谢谢提醒，我之前开发的时候没注意到官网这个模块化引入的方式
